package com.karlo.orionffa.storage;
import com.karlo.orionffa.statistics.PlayerStatistics;
import com.zaxxer.hikari.HikariConfig; import com.zaxxer.hikari.HikariDataSource;
import org.bukkit.configuration.file.YamlConfiguration; import org.bukkit.plugin.java.JavaPlugin;
import java.sql.*; import java.util.Arrays; import java.util.UUID; import java.util.concurrent.*;
public final class MySqlStorageProvider implements StorageProvider {
 private final HikariDataSource pool; private final ExecutorService executor=Executors.newFixedThreadPool(4,r->{Thread t=new Thread(r,"OrionFFA-MySQL");t.setDaemon(true);return t;});
 public MySqlStorageProvider(JavaPlugin plugin){HikariConfig c=new HikariConfig();String host=plugin.getConfig().getString("storage.mysql.host","localhost");int port=plugin.getConfig().getInt("storage.mysql.port",3306);String db=plugin.getConfig().getString("storage.mysql.database","orionffa");c.setJdbcUrl("jdbc:mysql://"+host+":"+port+"/"+db+"?useSSL=false&characterEncoding=utf8&serverTimezone=UTC&connectTimeout=3000&socketTimeout=5000");c.setUsername(plugin.getConfig().getString("storage.mysql.username",""));c.setPassword(plugin.getConfig().getString("storage.mysql.password",""));c.setMaximumPoolSize(Math.max(2,plugin.getConfig().getInt("storage.mysql.pool-size",10)));c.setMinimumIdle(Math.min(2,c.getMaximumPoolSize()));c.setConnectionTimeout(5000);c.setValidationTimeout(3000);c.setPoolName("OrionFFA-MySQL");pool=new HikariDataSource(c);initialize();}
 private void initialize(){try(Connection c=pool.getConnection();Statement s=c.createStatement()){s.executeUpdate("CREATE TABLE IF NOT EXISTS orionffa_stats (uuid VARCHAR(36) PRIMARY KEY,kills INT NOT NULL,deaths INT NOT NULL,kill_streak INT NOT NULL,best_kill_streak INT NOT NULL)");s.executeUpdate("CREATE TABLE IF NOT EXISTS orionffa_kits (uuid VARCHAR(36) NOT NULL,kit VARCHAR(64) NOT NULL,data LONGTEXT NOT NULL,PRIMARY KEY(uuid,kit))");}catch(SQLException e){close();throw new IllegalStateException("Cannot initialize MySQL storage: "+e.getMessage(),e);}}
 @Override public CompletableFuture<PlayerKitData> loadKit(UUID id,String kit){return CompletableFuture.supplyAsync(()->{try(Connection c=pool.getConnection();PreparedStatement s=c.prepareStatement("SELECT data FROM orionffa_kits WHERE uuid=? AND kit=?")){s.setString(1,id.toString());s.setString(2,kit);try(ResultSet r=s.executeQuery()){if(!r.next())return new PlayerKitData(new org.bukkit.inventory.ItemStack[0],new org.bukkit.inventory.ItemStack[0],null);YamlConfiguration y=new YamlConfiguration();y.loadFromString(r.getString(1));return new PlayerKitData(y.getList("inventory").stream().map(v->v instanceof org.bukkit.inventory.ItemStack i?i:null).toArray(org.bukkit.inventory.ItemStack[]::new),y.getList("armor").stream().map(v->v instanceof org.bukkit.inventory.ItemStack i?i:null).toArray(org.bukkit.inventory.ItemStack[]::new),y.getItemStack("offhand"));}}catch(Exception e){throw new IllegalStateException("Cannot load kit",e);}},executor);}
 @Override public CompletableFuture<Void> saveKit(UUID id,String kit,PlayerKitData d){return CompletableFuture.runAsync(()->{YamlConfiguration y=new YamlConfiguration();y.set("inventory",Arrays.asList(d.inventory()));y.set("armor",Arrays.asList(d.armor()));y.set("offhand",d.offhand());try(Connection c=pool.getConnection();PreparedStatement s=c.prepareStatement("INSERT INTO orionffa_kits(uuid,kit,data) VALUES(?,?,?) ON DUPLICATE KEY UPDATE data=VALUES(data)")){s.setString(1,id.toString());s.setString(2,kit);s.setString(3,y.saveToString());s.executeUpdate();}catch(SQLException e){throw new IllegalStateException("Cannot save kit",e);}},executor);}
 @Override public CompletableFuture<PlayerStatistics> loadStatistics(UUID id){return CompletableFuture.supplyAsync(()->{try(Connection c=pool.getConnection();PreparedStatement s=c.prepareStatement("SELECT kills,deaths,kill_streak,best_kill_streak FROM orionffa_stats WHERE uuid=?")){s.setString(1,id.toString());try(ResultSet r=s.executeQuery()){return r.next()?new PlayerStatistics(r.getInt(1),r.getInt(2),r.getInt(3),r.getInt(4)):PlayerStatistics.EMPTY;}}catch(SQLException e){throw new IllegalStateException("Cannot load statistics",e);}},executor);}
 @Override public CompletableFuture<Void> saveStatistics(UUID id,PlayerStatistics st){return CompletableFuture.runAsync(()->{try(Connection c=pool.getConnection();PreparedStatement s=c.prepareStatement("INSERT INTO orionffa_stats(uuid,kills,deaths,kill_streak,best_kill_streak) VALUES(?,?,?,?,?) ON DUPLICATE KEY UPDATE kills=VALUES(kills),deaths=VALUES(deaths),kill_streak=VALUES(kill_streak),best_kill_streak=VALUES(best_kill_streak)")){s.setString(1,id.toString());s.setInt(2,st.kills());s.setInt(3,st.deaths());s.setInt(4,st.killStreak());s.setInt(5,st.bestKillStreak());s.executeUpdate();}catch(SQLException e){throw new IllegalStateException("Cannot save statistics",e);}},executor);}
 @Override public String type(){return "mysql";} @Override public void close(){executor.shutdown();if(!pool.isClosed())pool.close();}
}
